parameters:
  kubernetes:
    control:
      role:
        patch:
          enabled: true
          kind: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - "pods"
              verbs:
                - "patch"
            - apiGroups:
                - ""
              resources:
                - "namespaces"
              verbs:
                - "get"
          binding:
            genie-pod-patch:
              subject:
                system:nodes:
                  kind: Group
