{%- from "kubernetes/map.jinja" import common with context -%}
{%- from "kubernetes/map.jinja" import pool with context -%}
{%- if pool.network.get('multus', {}).get('enabled') %}
---
{%- for delegates in pool.network.get('multus', {}).delegates %}
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ delegates.name }}
  {%- if delegates.type == "sriov" %}
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice_{{ delegates.phy_interface }}
  {%- endif %}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "{{ delegates.type }}",
      "name": "{{ delegates.name }}",
      {%- if delegates.type == "sriov" %}
      "master": "{{ delegates.phy_interface }}",
      {%- elif delegates.type == "bridge" %}
      "bridge": "{{ delegates.phy_interface }}",
      "isGateway": false,
      {%- endif %}
      "ipam": {}
    }
---
{%- endfor %}
{%- endif %}
