{% from "kubernetes/map.jinja" import control with context %}
apiVersion: {{ secret.apiVersion }}
kind: Secret
metadata:
  name: {{ secret_name }}
  namespace: {{ secret.get('namespace', 'default') }}
type: Opaque
{%- if secret.data is defined}
data:
  {%- if secret.data.type == 'ssl' %}
    {%- set ca_crt = salt['cmd.shell']('cat {0} | base64'.format(secret.data.ca_crt_file)) %}
    {%- set tls_crt = salt['cmd.shell']('cat {0} | base64'.format(secret.data.tls_crt_file)) %}
    {%- set tls_key = salt['cmd.shell']('cat {0} | base64'.format(secret.data.tls_key_file)) %}
  ca.crt: {{ ca_crt }}
  tls.crt: {{ tls_crt }}
  tls.key: {{ tls_key }}
  {%- else %}
    {%- for key, value in secret.data.secrets.items() %}
  {{ key }}: {{ salt['hashutil.base64_b64encode'](value) }}
    {%- endfor %}
  {%- endif %}
{%- endif %}
