{% from "kubernetes/map.jinja" import control with context %}
apiVersion: v1
kind: Service
metadata:
  {%- if service.role is defined %}
  labels:
    name: {{ service.service }}-{{ service.role }}
    app: {{ service.service }}-{{ service.role }}
  name: {{ service.service }}-{{ service.role }}
  {%- else %}
  labels:
    name: {{ service.service }}
    app: {{ service.service }}
  name: {{ service.service }}
  {%- endif %}
  namespace: {{ service.namespace }}
spec:
  ports:
    {%- for port in service.ports %}
    - port: {{ port.port }}
      name: {{ port.name }}
    {%- endfor %}
  type: {{ service.type }}
  selector:
    {%- if service.role is defined %}
    app: {{ service.service }}-{{ service.role }}
    {%- else %}
    app: {{ service.service }}
    {%- endif %}
  {%- if service.cluster_ip is defined %}
  clusterIP: {{ service.cluster_ip }}
  {%- endif %}
  {%- if service.external_ip is defined %}
  externalIPs:
  - "{{ service.external_ip }}"
  {%- endif -%}