{%- from "kubernetes/map.jinja" import common with context -%}
---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: kube-manager
  namespace: kube-system
  labels:
    app: kube-manager
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: kube-manager
  template:
    metadata:
      labels:
        app: kube-manager
    spec:
      hostNetwork: true
      containers:
      - name: opencontrail-kube-manager
        image: {{ common.addons.opencontrail.kube_manager.image }}
        securityContext:
          privileged: true
        env:
        - name: CONTRAIL_UID
          value: "{{ salt['user.info']('contrail').get('uid', 0) }}"
        - name: CONTRAIL_GID
          value: "{{ salt['group.info']('contrail').get('gid', 0) }}"
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - >
                apt update;
                apt install python-eventlet;
                service contrail-kube-manager restart;

        volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: etc-contrail
          mountPath: /etc/contrail
        - name: contrail-logs
          mountPath: /var/log/contrail
        - name: journal-kube-manager
          mountPath: /var/log/journal
        - name: etc-hostname
          mountPath: /etc/hostname
          readOnly: true

      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
          type: Directory
      - name: etc-contrail
        hostPath:
          path: /etc/contrail
          type: Directory
      - name: contrail-logs
        hostPath:
          path: /var/log/contrail
      - name: journal-kube-manager
        hostPath:
          path:  /var/log/journal/contrail-kube-manager
          type: DirectoryOrCreate
      - name: etc-hostname
        hostPath:
          path: /etc/hostname
          type: File

      nodeSelector:
        "node-role.kubernetes.io/master": "true"
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
